# =============================================================
# DealCraft — Neuro-SAN Studio Integration Client
# File: ui/neuro_san_client.py
# Version: v0.1.0
# Description: Wraps all communication between the Flask UI
#              and the Neuro-SAN Studio agent network.
#              Swap SIMULATION_MODE = False once API key arrives.
# =============================================================

import json
import os
import time

import requests

# -------------------------------------------------------------
# Configuration
# Toggle to False once your Claude API key is configured
# and Neuro-SAN Studio is running (python -m run)
# -------------------------------------------------------------
SIMULATION_MODE   = True
NEURO_SAN_HOST    = os.getenv('NEURO_SAN_SERVER_HOST', 'localhost')
NEURO_SAN_PORT    = int(os.getenv('NEURO_SAN_SERVER_HTTP_PORT', '8080'))
NEURO_SAN_NETWORK = 'dealcraft'  # matches registries/dealcraft.hocon filename


# -------------------------------------------------------------
# Simulated outputs used in SIMULATION_MODE for UI testing
# These give realistic output so you can demo the UI
# before the API key arrives
# -------------------------------------------------------------
SIMULATED_OUTPUTS = {

    'client-research-agent': """
# Client Intelligence Brief
## {client_name}
Generated by: DealCraft Client Research Agent
Date: {date}

---

### 1. Company Overview
[SIMULATION] {client_name} is a mid-sized organization operating in its sector
with a significant market presence. Headquartered in a major business hub,
the company employs several thousand professionals across multiple geographies.

### 2. Strategic Priorities
- Digital transformation and modernization of core systems
- Improving customer experience and digital channel capabilities
- Reducing operational costs through automation and AI
- Expanding into new markets and customer segments

### 3. Pain Points & Challenges
- Legacy technology infrastructure limiting agility
- Rising competition from digital-native players
- Increasing regulatory and compliance requirements
- Siloed data limiting insights and personalization

### 4. Recent News & Signals
- Recent leadership changes in Technology and Digital functions
- Announced multi-year digital transformation program
- Significant investments in cloud and data infrastructure

### 5. Technology Landscape
- Mix of legacy on-premise systems and newer cloud workloads
- Active evaluation of AI/ML capabilities
- Cloud migration partially underway

### 6. Cognizant Relationship
- New prospect / existing account (to be confirmed by BD team)

---
### Key Takeaways for BD Team
- Strong alignment with Cognizant's digital transformation capabilities
- AI and data modernization is a priority — lead with AI-first narrative
- Reference banking/FS transformation case studies for credibility
- Decision makers likely in Technology and Digital leadership
- Emphasize speed-to-value and risk reduction in proposal
""",

    'rfp-analyzer-agent': """
# RFP Analysis Summary
## {client_name}
Generated by: DealCraft RFP Analyzer Agent
Date: {date}

---

### 1. RFP Summary
[SIMULATION] Multi-year digital transformation engagement covering core systems
modernization, digital channel rebuild, and AI enablement. Estimated value
in the USD 25–40M range over 3 years.

### 2. Scope of Work
- Core platform modernization and migration
- Digital channel redesign (mobile, web, API)
- AI/ML implementation for automation and personalization
- End-to-end program management and governance

### 3. Key Requirements
- 10+ years transformation experience
- Proven delivery in relevant sector
- ISO 27001 / SOC 2 certifications
- Cloud platform expertise (AWS / Azure / GCP)
- Agile and DevSecOps delivery capability

### 4. Evaluation Criteria
- Technical Solution & Approach: 30%
- Relevant Experience & Case Studies: 25%
- Proposed Team & Governance: 15%
- Innovation & Differentiators: 15%
- Commercial Proposal: 15%

### 5. Timeline & Milestones
- Submission deadline: 5 weeks from issue date
- Program kick-off: 10 weeks from now
- Full delivery: 30 months

### 6. Fit Analysis — Cognizant
Strong fit across all major requirement areas. Key strengths:
cloud, AI/ML, digital engineering, and sector experience.

### 7. Red Flags & Risks
- Aggressive timeline for core migration
- Compliance requirements need dedicated workstream
- Parallel run complexity to be scoped carefully

---
### Top 5 Win Themes
- Proven large-scale transformation delivery with zero downtime
- AI-first approach embedded across all workstreams
- Dedicated sector centre of excellence
- Pre-built accelerators reducing time-to-value by 40%
- Strong local governance model with global delivery efficiency
""",

    'competitive-intel-agent': """
# Competitive Positioning Sheet
## {client_name}
Generated by: DealCraft Competitive Intel Agent
Date: {date}

---

### 1. Likely Competitors
1. Accenture — strong digital and cloud credentials
2. Infosys — competitive pricing, sector experience
3. Wipro — emerging AI capabilities, cost competitive
4. IBM — strong in core modernization, premium positioning
5. Capgemini — European strength, sector depth

### 2. Competitor Profiles

**Accenture**
- Strengths: Brand, digital transformation credentials, alliances
- Weaknesses: Premium pricing, sometimes over-engineered solutions
- Threat level: High

**Infosys**
- Strengths: Competitive pricing, sector depth, Finacle platform
- Weaknesses: Perceived as execution-only, less strategic advisory
- Threat level: High

**IBM**
- Strengths: Core banking modernization heritage
- Weaknesses: High cost, slower innovation pace
- Threat level: Medium

### 3. Cognizant Differentiation
- AI-first delivery model with embedded ML across all workstreams
- Sector-specific accelerators and pre-built assets
- Hybrid delivery model balancing cost and quality
- Strong partnerships with leading platform vendors
- Proven zero-downtime migration methodology

### 4. Positioning Strategy
Lead with outcomes, not technology. Position Cognizant as the
partner that combines strategic thinking with flawless execution.
Counter Accenture on value; counter Infosys on innovation depth.

### 5. Risk Assessment
Accenture is the primary threat — counter with sharper commercials
and stronger AI narrative. Infosys may undercut on price —
emphasize total cost of ownership and risk reduction.

---
### Recommended Differentiators for Proposal
- Zero-downtime migration track record (cite specific reference)
- AI-embedded delivery — not an add-on, but core to our approach
- Pre-built accelerators cutting delivery time by 30–40%
- Dedicated local governance team — not just offshore delivery
- Risk-based phasing approach reducing client exposure
""",

    'proposal-writer-agent': """
# Proposal Draft
## Digital Transformation Partnership — {client_name}
Prepared for: {client_name}
Prepared by: Cognizant Technology Solutions
Date: {date}
Version: Draft v0.1

---

## 1. Executive Summary

{client_name} stands at a pivotal moment in its transformation journey.
With core systems approaching end-of-life and digital competitors accelerating,
the imperative to modernize is both urgent and strategic.

Cognizant proposes a phased, risk-managed transformation program that delivers
tangible business outcomes at every stage — modernizing the core, reimagining
the digital experience, and embedding AI across the enterprise.

We bring proven delivery at scale, sector-specific accelerators, and an
AI-first methodology that differentiates this engagement from day one.

---

## 2. Understanding of Client Needs

[SIMULATION — to be tailored with real client intelligence]

We understand that {client_name} requires a trusted partner capable of:
- Managing complex legacy migration without business disruption
- Delivering a modern digital experience that matches customer expectations
- Embedding AI capabilities that drive measurable business outcomes
- Providing strong governance across a multi-year, multi-workstream program

---

## 3. Proposed Solution

Our solution is structured across three integrated workstreams:

**Workstream 1: Core Modernization**
Assessment → Platform selection → Parallel run → Cutover → Decommission

**Workstream 2: Digital Channels**
UX research → Design → Build → Test → Launch → Optimise

**Workstream 3: AI & Data Enablement**
Data platform → AI model development → Integration → Deployment → Monitor

---

## 4. Why Cognizant

- [INSERT CASE STUDY: Sector core banking migration reference]
- [INSERT CASE STUDY: AI-powered digital transformation reference]
- Pre-built accelerators reducing delivery time by 30–40%
- Dedicated sector centre of excellence with 5,000+ practitioners
- Active partnerships with leading platform vendors
- ISO 27001, SOC 2 Type II, sector compliance expertise

---

## 5. Value & Business Outcomes

| Outcome | Target |
|---------|--------|
| Reduction in transaction processing time | 75% |
| Improvement in digital channel NPS | +25 points |
| Reduction in fraud losses | 30% |
| Contact centre call deflection via AI | 40% |
| Total cost of ownership reduction | 20% over 3 years |

---

## 6. Engagement Model
Hybrid delivery — onshore governance and senior leadership,
offshore centre of excellence for development and testing.
Agile/SAFe delivery methodology with bi-weekly steering cadence.

---

## 7. Next Steps
- Proposal review meeting: Week of [DATE]
- Technical deep-dive session: Week of [DATE]
- Commercial discussion: Week of [DATE]

---
### Writer's Notes for BD Team
- Replace all [INSERT CASE STUDY] placeholders with real references
- Validate outcome targets with delivery team before submission
- Customize Section 2 with specific insights from client brief
- Add CVs of proposed key personnel in appendix
- Confirm commercial proposal is prepared separately
""",

    'report-assembler-agent': """
╔══════════════════════════════════════════════════════════════╗
║           DEALCRAFT BD PACKAGE                               ║
║           {client_name}                                      ║
║           Generated: {date}  |  Version: v0.1.0              ║
╚══════════════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  PACKAGE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{client_name} represents a high-value transformation opportunity in the
USD 25–40M range. Cognizant is well-positioned to win this engagement
given strong alignment between the client's requirements and our
capabilities in digital transformation, AI, and sector expertise.

Key Stats:
  Client              : {client_name}
  Opportunity Type    : Competitive RFP
  Est. Deal Value     : USD 25–40M / 3 years
  Top Competitor      : Accenture
  Our Key Differentiator: AI-first delivery with pre-built accelerators

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  DOCUMENT 1 — CLIENT INTELLIGENCE BRIEF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[See Client Research Agent output above]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  DOCUMENT 2 — RFP ANALYSIS SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[See RFP Analyzer Agent output above]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  DOCUMENT 3 — COMPETITIVE POSITIONING SHEET
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[See Competitive Intel Agent output above]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  DOCUMENT 4 — PROPOSAL DRAFT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[See Proposal Writer Agent output above]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  BD TEAM CHECKLIST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Must Do:
  ☐ Validate all client research facts with account team
  ☐ Fill in all [INSERT ...] placeholders in proposal
  ☐ Validate outcome targets with delivery leadership
  ☐ Prepare commercial proposal (separate document)
  ☐ Get leadership sign-off on solution approach

  Recommended:
  ☐ Add 2 real case studies with client permission
  ☐ Customize cover page with client branding
  ☐ Schedule pre-submission review with client contact

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by DealCraft v0.1.0 — AI-Powered BD Command Center
Built on Neuro-SAN Studio | Cognizant AI Lab
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
}


# -------------------------------------------------------------
# DealCraft Client
# -------------------------------------------------------------

class DealCraftClient:
    """
    Wrapper for Neuro-SAN Studio agent calls.
    Set SIMULATION_MODE = False and implement _call_neuro_san()
    once your Claude API key is configured.
    """

    def __init__(self):
        self.simulation = SIMULATION_MODE
        self.base_url   = f'http://{NEURO_SAN_HOST}:{NEURO_SAN_PORT}'

    def run_agent(
        self,
        agent_id: str,
        client_name: str,
        rfp_text: str,
        previous_outputs: dict
    ) -> str:
        """
        Run a single agent and return its text output.
        Dispatches to simulation or real Neuro-SAN based on mode.
        """
        if self.simulation:
            return self._simulate(agent_id, client_name)
        else:
            prompt = self._build_prompt(
                agent_id, client_name, rfp_text, previous_outputs
            )
            return self._call_neuro_san(agent_id, prompt)

    def run_leadership_review(
        self,
        existing_output: str,
        leadership_input: str,
        revision: int,
        client_name: str
    ) -> str:
        """Run the leadership-review-agent on an existing BD package."""
        if self.simulation:
            return self._simulate_review(existing_output, leadership_input, revision, client_name)
        prompt = (
            f'Existing BD Package:\n{existing_output}\n\n'
            f'Leadership Input (Revision R{revision}):\n{leadership_input}'
        )
        return self._call_neuro_san('leadership-review-agent', prompt)

    def _simulate_review(
        self,
        existing_output: str,
        leadership_input: str,
        revision: int,
        client_name: str
    ) -> str:
        import datetime
        time.sleep(3)
        header = (
            f'╔══════════════════════════════════════════════════════════════════╗\n'
            f'║  DEALCRAFT BD PACKAGE — REVISED                                  ║\n'
            f'║  Client: {client_name:<20}  |  Revision: R{revision:<20}║\n'
            f'║  Generated: {datetime.date.today().isoformat()}  |  Incorporating: Leadership Review  ║\n'
            f'╚══════════════════════════════════════════════════════════════════╝\n\n'
        )
        revision_summary = (
            f'\n\n{"━"*66}\n'
            f'  REVISION SUMMARY — What Changed in R{revision}\n'
            f'{"━"*66}\n\n'
            f'Leadership Input Received: {leadership_input[:200]}{"..." if len(leadership_input) > 200 else ""}\n\n'
            f'Changes Made:\n'
            f'| Section              | What Changed                        | Triggered By          |\n'
            f'|----------------------|-------------------------------------|-----------------------|\n'
            f'| Executive Summary    | Win themes updated per direction    | Leadership feedback   |\n'
            f'| Why Cognizant        | Differentiators reprioritized       | Leadership feedback   |\n'
            f'| Competitive Positioning | Counter-strategy refined         | Leadership feedback   |\n\n'
            f'Unchanged: All other sections preserved from previous version.\n\n'
            f'{"━"*66}\n'
            f'Generated by DealCraft v0.1.0 — AI-Powered BD Command Center\n'
            f'{"━"*66}\n'
        )
        # Strip the old header box (╔...╚...╝\n\n) and keep the body after it
        if '╚' in existing_output:
            # Everything after the closing box line
            parts = existing_output.split('\n')
            body_lines = []
            past_header = False
            for line in parts:
                if past_header:
                    body_lines.append(line)
                elif '╚' in line:
                    past_header = True
            body = '\n'.join(body_lines).strip()
        else:
            body = existing_output.strip()
        return header + body + revision_summary

    # ----------------------------------------------------------
    # Simulation Mode
    # ----------------------------------------------------------

    def _simulate(self, agent_id: str, client_name: str) -> str:
        """Return realistic simulated output for UI testing."""
        import datetime
        template = SIMULATED_OUTPUTS.get(agent_id, f'[{agent_id} output]')
        time.sleep(2)   # Simulate processing time for realistic progress UX
        return template.format(
            client_name=client_name,
            date=datetime.date.today().isoformat()
        )

    # ----------------------------------------------------------
    # Neuro-SAN Integration (activate when API key is ready)
    # ----------------------------------------------------------

    def _build_prompt(
        self,
        agent_id: str,
        client_name: str,
        rfp_text: str,
        previous_outputs: dict
    ) -> str:
        """Build the appropriate input prompt for each agent."""
        ctx = '\n\n'.join(
            f'=== {k} ===\n{v}' for k, v in previous_outputs.items()
        )

        prompts = {
            'client-research-agent': (
                f'Research this client and produce a Client Intelligence Brief:\n'
                f'Client Name: {client_name}'
            ),
            'rfp-analyzer-agent': (
                f'Analyze the following RFP document and produce an RFP Analysis Summary:\n\n'
                f'{rfp_text}'
            ),
            'competitive-intel-agent': (
                f'Using the context below, produce a Competitive Positioning Sheet '
                f'for a deal with {client_name}.\n\n{ctx}'
            ),
            'proposal-writer-agent': (
                f'Using all the research below, write a tailored proposal draft '
                f'for {client_name}.\n\n{ctx}'
            ),
            'report-assembler-agent': (
                f'Assemble all the outputs below into a final DealCraft BD Package '
                f'for {client_name}.\n\n{ctx}'
            ),
        }
        return prompts.get(agent_id, f'Run agent {agent_id} for client {client_name}')

    def _call_neuro_san(self, agent_id: str, prompt: str) -> str:
        """
        Call the Neuro-SAN Studio streaming chat API.

        The API addresses the *network* (not individual agents).
        The orchestrator agent inside the network handles delegation.
        The agent_id param is kept for logging/context but the request
        goes to the network endpoint.

        Endpoint: POST /api/v1/{network}/streaming_chat
        Payload:  {"user_message": {"type": "HUMAN", "text": "..."}}
        Response: application/json-lines (one JSON object per line)
        """
        url = f'{self.base_url}/api/v1/{NEURO_SAN_NETWORK}/streaming_chat'
        payload = {
            'user_message': {
                'type': 'HUMAN',
                'text': prompt
            }
        }

        try:
            response = requests.post(url, json=payload, stream=True, timeout=300)
            response.raise_for_status()
        except requests.ConnectionError:
            return (
                f'[Error] Cannot connect to Neuro-SAN server at {self.base_url}. '
                f'Start the server with: python -m run --server-only'
            )
        except requests.RequestException as e:
            return f'[Error] Neuro-SAN API call failed: {e}'

        # Parse streaming JSON-lines response — extract final answer
        last_text = ''
        for line in response.iter_lines(decode_unicode=True):
            if not line or not line.strip():
                continue
            try:
                result = json.loads(line)
                resp = result.get('response', {})
                chat_context = resp.get('chat_context', {})
                histories = chat_context.get('chat_histories', [])
                if histories:
                    messages = histories[-1].get('messages', [])
                    if messages:
                        text = messages[-1].get('text', '')
                        if text:
                            last_text = text
            except json.JSONDecodeError:
                continue

        return last_text or f'[No response from Neuro-SAN for agent {agent_id}]'